name: xeus-sql
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  - cxx-compiler
  - ninja
  # host dependencies
  - cpp-tabulate>=1.5
  - cppzmq
  - nlohmann_json
  - soci-core
  - xeus-zmq=1.1.1
  - xproperty=0.11.0
  - xtl
  - xvega-bindings=0.0.10
  - xvega=0.0.10
  # Test dependencies
  - doctest >= 2.4.6
