name: xeus-sql
channels:
  - conda-forge
dependencies:
  # Builde dependencies
  - cmake
  # host dependencies
  - xeus=2.0.0
  - cppzmq
  - nlohmann_json
  - xtl=0.7.2
  - cpp-tabulate
  - soci-core
  - xproperty=0.11.0
  - xvega-bindings=0.0.10
  - xvega=0.0.10
